### ISSUE TITLE
miaolz123/vue-helmet comparison

### ISSUE THREAD

**Issue by ghost** [jnields/vue-helmet#1]
Any pros/cons against this project? https://github.com/miaolz123/vue-helmet

**Comment by jnields** [comment]
That project might be OK smaller apps but it doesn't offer support for server rendering and appears to have a small subset of the features offered here.

At a first glance it appears to be missing support for style tags, body attributes, noscript tags, and subscribing to changes. I'm not sure, but it also appears it won't update tags on prop changes - though I haven't confirmed this. It also does not appear to be production-ready as it has no tests.

This is module is fairly full-featured and production ready.
